// Punto de entrada del banco de pruebas: Vite lo empaqueta a dist/pruebas y Node lo corre con node:test.
// Ver `npm run prueba`.
import './esquema.prueba'
import './normalizar.prueba'
import './importador.prueba'
import './bordes.prueba'
import './correcciones.prueba'
import './hoja-real.prueba'
import './semaforo.prueba'
import './cartera.prueba'
import './sincronizacion.prueba'
import './fuente-google.prueba'
import './polizas-helpers.prueba'
import './clientes.prueba'
import './deudores.prueba'
import './polizas.prueba'
import './renovaciones.prueba'
import './cobranzas.prueba'
import './siniestros.prueba'
import './fase8.prueba'
import './fase9.prueba'
import './github-contents.prueba'
import './usuarios-remotos.prueba'
